description: Requires authentication
get:
  summary: Gets all roles available
  description: Supports guest users. Gets all roles available
  tags:
    - Roles
  security:
    - BearerAuth: []
  responses:
    "200":
      description: Successful request
      content:
        application/json:
          schema:
            type: object
            properties:
              roles:
                type: array
                items:
                  type: object
                  properties:
                    roleId:
                      type: number
                    roleName:
                      type: string
    "500":
      $ref: "../../responses.yml#/500"
    "403":
      $ref: "../../responses.yml#/403"
    "401":
      $ref: "../../responses.yml#/401"
