name: Build docs

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Bundle rest api
        run: npx @redocly/cli@latest bundle ./apiSpec/$1/openapi.yml -o ./apiSpec/bundled.yml
      - name: Bundle asyncapi
        run: cd apiSpec/v1 && npx @asyncapi/cli@latest bundle asyncapi.yml >../asyncapi-bundled.yml && cd ../..
      - name: Generate asyncapi docs
        run: cd apiSpec/ && npx @asyncapi/cli@latest generate fromTemplate asyncapi-bundled.yml @asyncapi/html-template -o ../docs && cd ../
      - name: Set git origin
        run: git remote set-url origin git@github.com:TofuDotTech/CrujofestApiDocs.git
      - name: Check for changes
        run: git status
      - name: Stage changed files
        run: git add .
      - name: Commit changed files
        run: git commit -m "Specs bundled and docs generated"
      - name: Fetch from main
        run: git fetch origin main
      - name: push code to main
        run: git push origin HEAD:main
